### ISSUE TITLE
Pls make an app client 

### ISSUE THREAD

**Issue by Raif1** [TheDavidDelta/lingva-translate#101]

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in this project!

Lingva is a web app. It can be used within a browser or, thanks to the PWA standard, can be encapsulated into an app-like shortcut in your system. You just have to go to the webpage in a PWA supported browser (unfortunately, mostly Chromium-based) and click "install" in the search bar.

But Lingva is also a service with its own public API, as described in the Readme. It's Free and Open Source Software that anyone can extend or contribute to! The following projects used our API in order to integrate Lingva into their software.

If you prefer a more native experience, [CrowTranslate](https://github.com/crow-translate/crow-translate) is a Qt-based multiplatform app for translating texts that uses several translation engines, including Lingva.
In case you use Android, another community member has also developed [Lentil](https://github.com/yaxarat/lingvaandroid), a translation app that uses Lingva's public API.

Hope you find this useful.

Regards, David.
