### ISSUE TITLE
Lingva translate doesn't work currently on Ubuntu touch

### ISSUE THREAD

**Issue by gbdomubpkm** [thedaviddelta/lingva-translate#118]
Hello @thedaviddelta 
Have you done anything very recently on Lingva translate that prevents the web link from working correctly now on Ubuntu Touch smartphones ? I find myself (Volla Phone) with a wheel that spins endlessly in the translation part even if there is nothing to translate.
Regards
![screenshot20220617_052643728](https://user-images.githubusercontent.com/50362604/174266071-0cb6c1d6-9a84-4649-9a1a-911b08afa86f.png)

**Comment by thedaviddelta** [comment]
Hello!

Yes, recently I uploaded a pretty big Lingva update (#113).
It added several things, as listed there, but always trying to follow the compatibility with the current web standards.
Unfortunately, there are some browsers that can't keep up to date, and maybe doesn't support certain kind of new (or not that new) features.

I don't have Ubuntu Touch or any way of testing its integrated browser, either, so can't debug the problem.
If someone is able to, and the fix doesn't sacrifice any feature, feel free to PR.
Otherwise, you can also use the [unofficial Ubuntu Touch native app](https://github.com/walking-octopus/translate-ut) that a community member developed using Lingva's API.

I hope this helped.
Regards, David.

**Comment by gbdomubpkm** [comment]
Thank you for your reply.@thedaviddelta .

On android, Firefox, Vivaldi, Brave, Privacy Browser seem to work well with your mentioned update.

Concerning the very recent current malfunction of lingva translate under morph-browser (UT), maybe a recent update of QtWebengine in development/test phase will solve the problem. I do not know yet.

Concerning translate-ut, I know this app very well since I informed you about it 😉; it works better and better!!
Best regards
