### ISSUE TITLE
A Chromium extension would be great

### ISSUE THREAD

**Issue by quarkl8** [thedaviddelta/lingva-translate#121]
Thanks so much for this frontend! I found a Lingva extension for [([](Firefox)](https://addons.mozilla.org/en-US/firefox/addon/lingva/) but couldn't find anything for Chromium browsers like Brave, that would be really great to have!

**Comment by thedaviddelta** [comment]
Hi and thanks for your interest in this project.

This has already been requested in #22 and #75.
The Lingva project is meant to be a webapp serving as a Free and Open Source front end for Google Translate.

We aren't intending to make addons ourselves, but we have a great API, both in REST and GraphQL, as well as an NPM package, for making use of our scraping.
So basically anyone can make a project using Lingva as a base, as some people mentioned on our Readme already created Android or UbuntuTouch native apps.

That Firefox extension isn't ours, but made by someone else in the community using our APIs. I didn't even know about it. Unfortunately, it seems it's using our name and logo instead of creating a new identity, as I usually recommend doing. There's nothing that stops people from using the Lingva name, as it's a community-driven project, but in my opinion they shouldn't because it can be confusing for people like you.

I don't know if anyone has already created an addon for Chromium, but indeed it's pretty easy to run a Firefox addon there. Make an issue in his repository requesting it, or try it by yourself using the [WebExtensions polyfill](https://github.com/mozilla/webextension-polyfill).

I hope all this helped.
Regards, David.
