### ISSUE TITLE
Is it possible to prepare a link for translation?

### ISSUE THREAD

**Issue by Duckbilled** [TheDavidDelta/lingva-translate#13]
I would like to set two specific languages (from - to), but if I try lingva.ml/en/xx/ it directs me to lingvia.ml/auto/en/xx/. Is there a correct way to do this? This way I can circumvent scrolling true all the languages each time.

**Comment by TheDavidDelta** [comment]
Hi and thank for your interest in the project.

Sorry, it's not possible because another approach is already considered for a 2-length path. I'll try to explain myself.
For a 1-length path, the default behaviour is to use it as the translation query, selecting both languages automatically (Detect - English). For a 2-length path, it may be considered to prepare two specific languages and an empty translation as you say or, following the previous logic, to take the last path part as the translation query, and left the first part as the target language. That way you're able to query a translation from `auto` (Detect) to an specified language.
I'd be cool being able to do both, but it's not possible, and I thing it has more sense the way it's now. Anyway if a lot of people agrees with you I may change it in the future.

Regards, David.
