### ISSUE TITLE
Zombie process production in docker mode

### ISSUE THREAD

**Issue by thantez** [thedaviddelta/lingva-translate#143]
Hi. I thank you for this useful project.
After a time of config self-hosted Lingva and using it based on docker, Ubuntu attend me that some zombie processes exist. First I checked what is the command of these zombies, and this is the result:
![image](https://user-images.githubusercontent.com/33148504/200304118-f54f992e-2d56-4a7a-9f49-ba40c5cb2b59.png)

After that, I checked this processes, are belongs to which parent?
![image](https://user-images.githubusercontent.com/33148504/200304261-5e17ec41-c013-449d-9140-838245b04d5f.png)

Until there, I found there is a node.js based project that make zombies. So I checked which parent process call this `yarn start` command:
![image](https://user-images.githubusercontent.com/33148504/200304511-0692f070-1bcf-41b9-9c1c-b8b7c49d28ec.png)

and I checked which container uses this ID:
![image](https://user-images.githubusercontent.com/33148504/200304652-15875847-9d04-47a4-9ce9-7c3bda168fc6.png)

Based on this clues, I had this hypothesis that probably this problem caused by Lingva container. For the proof, I do these steps:
1. check Lingva project that is based on node.js: Yes it is ✅
2. If I stop Lingva container, zombies should die,
![image](https://user-images.githubusercontent.com/33148504/200305239-49d85865-dab0-4543-bc04-a4784feb2f02.png)
and yeah, they died. ✅

So I don't know how, but I know Lingva docker image produce some zombie processes that this is the issue.

---

* Ubuntu kernel version: 5.4.0-131-generic
* Docker version: 20.10.18, build b40c2f6
* Lingva image tag: latest created 2 weeks ago

If you need other information, tell me.

**Comment by thedaviddelta** [comment]
Hello and sorry for the late response.

I did read this some time ago but forgot to answer, because I didn't have much to contribute, I'm sorry.
I don't actively host Lingva with Docker, just have created several containers in my local machine while developing, maintaining and testing the Docker version. In those chances, I didn't notice any issue.
Maybe if some other people suffer from this issue and report it we can get a wider view, with multiple possible explanations, and start to narrow it. For the moment, I'd just recommend you to restart the process from time to time if this still happens to you.

Thanks and regards, David.

**Comment by camporter** [comment]
Could you try with `--init` using `docker run`, or in `docker-compose`, `init: true`: https://docs.docker.com/compose/compose-file/compose-file-v2/#init

I'm guessing since there's no init process inside the container, there's nothing that can reap the zombie processes. This also seems to be a common problem with docker `HEALTHCHECK`.

The readme could be updated to reflect this.

**Comment by thedaviddelta** [comment]
Amazing! Thank you so much for your help @camporter!
May then removing `HEALTHCHECK` from the Dockerfile also solve this issue without adding an init proccess?

Could you please try this (both just removing `HEALTHCHECK`, and just adding `--init`) and report whether this solves your issue @thantez? I'd then edit the project's Dockerfile, or add the parameter to the `README`.

Thanks again and regards, David.

**Comment by thantez** [comment]
> Could you please try this (both just removing `HEALTHCHECK`, and just adding `--init`) and report whether this solves your issue @thantez? I'd then edit the project's Dockerfile, or add the parameter to the `README`.

Thanks for your efforts. I don't know why but now its OK without any changes. The healthcheck exists and init is not considered. I think after this long time something fixed the issue.
