### ISSUE TITLE
Detected language is not shown

### ISSUE THREAD

**Issue by jcbrand** [thedaviddelta/lingva-translate#17]
Hi David

Thanks for creating this, I just tried this out after seeing your fediverse post.

I noticed that the detected language is not shown, so you don't actually know as what language a phrase was detected as.

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in this project!

This is a cool feature I'd like to have implemented in the first place, but wasn't able because Lingva uses the [mobile version of GTranslate](https://translate.google.com/m) for scrapping, which doesn't display the detected language.
Anyway when I get the time in the future, I'm planing to take a look about if it's practical to scrape the main page for adding the functionalities requested in #8, so I'll also let this issue open as a future enhancement until then.

Regards, David.

**Comment by thedaviddelta** [comment]
Hey!
I'm glad to tell you that, in the latest big update (#113) this feature was finally added, as well as other cool ones, thanks to a newly discovered endpoint.
Hope you enjoy it!

Regards, David.

**Comment by xamax71** [comment]
Hi David,
I just found out about your project and I would like to use it to translate the product reviews on my site.

I have been trying to get the value of the detected language but without success.

So I am reopening this thread rather than creating a new one.

With the REST API the response I get is:

`{"translation": String}`
```
instead of

{
    translation: string
    info?: TranslationInfo
}
```
as shown in the readme.

I've tried using graphql too

```
query {
  translation(
    source: "auto"
    target: "fr"
    query: "Hi, today is a good day"
  ) {
    source {
      lang {
        code
        name
      }
      text
      detected {
        code
      }
    }
    target {
      lang {
        code
        name
      }
      text     
    }
      
  }
}
```

and in the response I get `detected: null`; All the other fields are populated correctly.

Now, when I try to translate a string from your web instance I can see in the response 

```
...

"info": {
            "detectedSource": "en",
            "pronunciation": {},
            "definitions": [],
            "examples": [],
            "similar": [],
            "extraTranslations": []
        },
...
```

So, I would like to ask you if it is possible to get the detected value of the string with the API.

The purpose is to translate only the reviews that are not already in the target language.

Thank you,
Massimo

**Comment by Stypox** [comment]
I can confirm the API does not return the detected language, which would be helpful to improve https://github.com/Stypox/dicio-android/pull/331
