### ISSUE TITLE
Typing in a URL leads to a 404 redirect

### ISSUE THREAD

**Issue by theontho** [TheDavidDelta/lingva-translate#18]
This is the URL rewrite that your JS code creates: https://lingva.ml/auto/nl/http%3A%2F%2Fnews.ycombinator.com

input text: 'https://news.ycombinator.com'

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in the project.

I've been testing this and it seems to be a problem of the translations including slashes, not only links (i.e. https://lingva.ml/en/es/like%20%2F%20dislike), even though they are correctly encoded with `encodeURIComponent` and work as expected locally.
I've open an issue in the NextJS official repo linking this one, because they are the maintainers of both the framework and the hosting service I'm using. Let's see what they reply.

Regards, David.

**Comment by TheDavidDelta** [comment]
Hello again.

They took a long time but finally fixed this problem and replied to my issue.
It's already available in a canary version, which I just tested in a preview branch.

[Here](https://lingva.ml/auto/nl/http%3A%2F%2Fnews.ycombinator.com)'s your example URL and [this](https://lingva-translate-git-update-dependencies-u-7b87d2-thedaviddelta.vercel.app/auto/nl/http%3A%2F%2Fnews.ycombinator.com) is it working currently in the updated branch.
In addition, [here](https://lingva.ml/en/es/like%20%2F%20dislike)'s an example I did on my issue and [this](https://lingva-translate-git-update-dependencies-u-7b87d2-thedaviddelta.vercel.app/en/es/like%20%2F%20dislike) is its current behaviour.

I'll merge to production when it's released on their next stable version, but just wanted you to know that it's fixed.

Regards, David.

**Comment by TheDavidDelta** [comment]
The fix is finally available on a stable version.
The update will be merged to main in the following hours.
