### ISSUE TITLE
Translations comparison

### ISSUE THREAD

**Issue by itsnotsaved** [TheDavidDelta/lingva-translate#24]
![image](https://user-images.githubusercontent.com/73447325/119939323-de093d80-bfb7-11eb-8097-a08b489d91fc.png)
https://imtranslator.net/Translation-Comparison-for-Chrome.asp

**Comment by itsnotsaved** [comment]
https://github.com/TheDavidDelta/lingva-translate/issues/10

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in this project.

As you can see in the issue you mentioned, Lingva still doesn't support multiple backends and only scrapes GTranslate at the moment. This is a good idea to add once the project supports that enhancement, but doesn't have much sense at the moment.
I'd ask you to join this issue inside the other because they have direct correlation, but it's not needed because you already linked the issues, so I'll just close this one and keep track of it in the other one.

Regards, David.
