### ISSUE TITLE
Do not interact processing with source editing

### ISSUE THREAD

**Issue by IniUe** [TheDavidDelta/lingva-translate#30]
**Problem Description**

Currently it seems lingva let specific time to type word or sentence on source window. i mean it wait specific time after user stopped type, once it exceeded then start to process for translate it.
During process, lingva doesn't allow to type anything on source window however seldom it's possible to modify sentences or type more but once finished translation next recent changes automatically get discarded.

**Expected Behavior**

Allow users to edit or type more on source window during process then once done recent task next it should check again if there any changes; if any then it must translate content on source window once again.

**Comment by TheDavidDelta** [comment]
Hi again and thanks for your interest in the project.

This problem is not very easy to solve with the current way Lingva behaviours. The external request isn't done using AJAX but directly on the server-side, for the server to cache the static generated page. Also, its response modifies the query input too.

But I've been thinking about changing the auto-translate behaviour since the relase. Because of personal usage and users feedback I think it may be better to disable auto-translate by default and add a manual translate button. Also, optionally, you can enable auto-translation with another button.

I've already added this in my last PR, merging in a little while. Hope y'all like it.

Regards, David.
