### ISSUE TITLE
Add paste button to source window

### ISSUE THREAD

**Issue by IniUe** [TheDavidDelta/lingva-translate#31]
This is a minor enhancement.

Add a paste button to source window (near to play button) then user able to paste any clipboard contents without right-click - paste or ctrl+v (keyboard)

**Comment by TheDavidDelta** [comment]
Hi again and thanks for your interest in the project.

Sorry for not adding this but I've been reading about the paste API and it's not that easily usable as the copy one.
Basically, it's not directly me but a UI library who has an encapsulated function that internally copies the text. I've been reading its code and it uses `document.execCommand`. The problem is that the paste action in `execCommand` isn't supported by any browser other than Internet Explorer.
The other solution may be to use the official clipboard API but it'd request user permissions (just like notifications) and wouldn't be worth it.

Regards, David.

**Comment by sayuri-gi** [comment]
See https://igram.io

**Comment by sayuri-gi** [comment]
@thedaviddelta why deleted? i mean it has "paste" button https://igram.io/
chromium edge build (tested)

**Comment by sayuri-gi** [comment]
I noticed it doesn't work on linux

**Comment by thedaviddelta** [comment]
I'm very sorry @sayuri-gi, I thought it was some kind of scam spam, but I can't undo the deletion.
Which method pasting method is it using?

**Comment by sayuri-gi** [comment]
See https://igram.io/
It worked on windows with vivaldi browser but doesn't work on my linux machine with chromium

**Comment by thedaviddelta** [comment]
But I can't see the inner code. Is it open source or something?
