### ISSUE TITLE
Option to clear contents without affect to language selection

### ISSUE THREAD

**Issue by IniUe** [TheDavidDelta/lingva-translate#32]
From https://github.com/TheDavidDelta/lingva-translate/issues/9

When click on the logo, it clear contents as expected but with language selection then user has to choose language again if translate to same language and gtranslate doesn't has this behavior

I prefer suggest below options,

1. Add two different feature to "lingva" and "translate". In this case, you have to customize the logo. I see this as flexible and something new.
  a. if click on lingva, then clear all contents including language selection
  b. if click on translate, then only clear contents that contain on windows
     (or you can add "clear/symbol" button to source window instead)

2. When tap on the logo then remove contents without clear language selection (as gtranslate)

3. Ignore this enhancement

**Comment by TheDavidDelta** [comment]
Hi again and thanks for your interest in the project.

I think the way it currently works is the better and I'll try to explain why.

Lingva uses the app's URLs to decide the source, target and query data. Each page is then static generated and stored using that data. That way, the next time the same translation is requested, the response would be automatic because the page was already generated.

With this mindset, the `/` page (let's call her *home*) should have the default values (source: auto, target: en, empty query, and other internal values) both when first requested and when returned using the logo link.

Tell me what do you think about this.

Regards, David.
