### ISSUE TITLE
Mixing lingva with https://www.newocr.com/

### ISSUE THREAD

**Issue by yesNOmaybe69420pogchamp69** [TheDavidDelta/lingva-translate#34]
Just a suggestion. Is it possible to mix these 2 services? Then, we could have ocr in lingva just google transalate

https://www.newocr.com/

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in the project.

The problem with the service you linked is that it's not even open source. In addition, its API is paid after the 20 free first images.
It would be indeed a nice idea to add some kind of OCR functionality, but using Tesseract or any of the other open source OCR libraries instead of relaying on a external service.
But anyway by the moment I think this is more like a far-future addition

**Comment by yesNOmaybe69420pogchamp69** [comment]
Thanks for your response!

**Comment by TheDavidDelta** [comment]
You're welcome! And thanks for your suggestion.
