### ISSUE TITLE
Docker image for the project

### ISSUE THREAD

**Issue by grubeli** [TheDavidDelta/lingva-translate#42]
It would be easy to integrate the project self-hosted services if we could have a docker-compose file, building docker-compose for NextJS is pretty easy and I guess it would help everyone

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in this project.

I've been playing with Docker for a few hours and I'll tell you my initial outcome.
Because Lingva is simply a _scraper_ and doesn't need volumes, I think it doesn't need docker-compose (even though I'm beginner with Docker) and I'm just trying to build an image and push it to Docker Hub.

The problem is that Lingva requires the instance host to specify an environment variable called `NEXT_PUBLIC_SITE_DOMAIN` for the canonical URL and the meta tags, and it's needed at **buildtime**. I've been trying to elude this throught different ways but I couldn't manage to generate a compiled image that allowed to specify the variable.

If you have any idea on how to cope with this please tell me. Otherwise I could just commit the `Dockerfile` for easing the manual compilation but without pushing any official image.

Regards, David.

**Comment by grubeli** [comment]
I think you can provide env variables to docker-compose

**Comment by TheDavidDelta** [comment]
Yes, I can. I also can provide both arguments and environment variables to the Dockerfile. The problem is that they're only used for building a *new* image (before publishing), or for running an *already* existing image (but only for runtime, not for buildtime). As far as I know, docker-compose is only used for running a group of images altogether, and probably with some volumes, but it doesn't solve this problem.

**Comment by TheDavidDelta** [comment]
Hello again.

I'm happy to tell you that I was finally able to cope with the problem. What I decided to do is to run the final `yarn build` command, which generates the static pages, in the CMD along with `yarn start`. This way, you're able to configure your page build (in this case by specifying the site domain).

The image is already available in [Docker Hub](https://hub.docker.com/repository/docker/thedaviddelta/lingva-translate).

Regards, David.

**Comment by grubeli** [comment]
thank you

**Comment by TheDavidDelta** [comment]
Amazing!
