### ISSUE TITLE
Not working with blocked cookies

### ISSUE THREAD

**Issue by alefvanoon** [TheDavidDelta/lingva-translate#43]
![image](https://user-images.githubusercontent.com/53198048/132031488-5253d2f8-3cb6-4a04-9824-db0c1eaa9205.png)
When i'm trying to block cookies with brave browser extension:
![image](https://user-images.githubusercontent.com/53198048/132031526-5a6359cd-67a4-4c1e-9b58-06ec1390f7c5.png)

**Comment by TheDavidDelta** [comment]
Hi again!

I did a quick search about this and found out that most browsers (including Chromium) disables access to `localStorage` when blocking all cookies. I think this may even be evil because there's no way of avoiding this other that wrapping every `localStorage` call with a `try/catch` block, so this way they discourage users to block them.

Anyway, I simply did that (wrap them inside `try/catch`es) and tested it on Brave (my second browser) and now it's working correctly. [Give it a try!](https://lingva-translate-git-localstorage-with-blo-9a46a4-thedaviddelta.vercel.app). Will merge later.

Regards, David.

**Comment by alefvanoon** [comment]
Hi!
Thanks for your attention.
I tried the new version and it worked great without cookies. :)
Thanks again.

**Comment by TheDavidDelta** [comment]
No problem! I've also solved this in TheDavidDelta/kainet-music#8.

**Comment by alefvanoon** [comment]
> No problem! I've also solved this in [TheDavidDelta/kainet-music#8](https://github.com/TheDavidDelta/kainet-music/pull/8).

Yes, this PR is what I meant. :)
