### ISSUE TITLE
Possible to add custom translation?

### ISSUE THREAD

**Issue by shan52** [TheDavidDelta/lingva-translate#49]
Is it possible to add custom translation?

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in the project.

Sorry but this is not possible. This is because Lingva is not an independent translation engine, but a FOSS front-end for GTranslate, so we can't add new words to the engine.
If you need to add any word you could do it directly from the GTranslate original service, thought I don't recommend doing this because it implies using and contributing to Google services.

Regards, David.
