### ISSUE TITLE
Not an issue but help needed!

### ISSUE THREAD

**Issue by milesmcclane** [TheDavidDelta/lingva-translate#63]
Firstly - amazing project. Been looking for something like this for ages. Well done and keep up the good work. 
I’m self hosting an instance, and I wanted to be able to use this string, but I can’t get it to work. What would I need to change to make it compatible with lingva? It’s so I can search directly from the search bar. 
https://translate.google.com/?sl=auto&tl=en&text=%s&op=translate
Thanks!

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in the project.

I'm glad you make me this question. I indeed built the Lingva URL with intention of having a pretty and useful URL. It has the following structure:
```
https://<domain>/<sourceLang>/<targetLang>/<query>
```

But, indeed, you can omit parameters:
```
// with 2 params (sourceLang defaults to "auto")
https://<domain>/<targetLang>/<query>

// with 1 param (sourceLang defaults to "auto" & targetLang to "en")
https://<domain>/<query>
```

So, for building your custom search query in your browser, you should use the following URL:
```
https://<yourDomain>/auto/en/%s

// or simply
https://<yourDomain>/%s
```

But, as an additional note, I'll tell you that I like using custom browser searchers myself. So I built a little more complex search query for my personal use using a tiny JavaScript trick:
```
javascript: location.replace(`https://lingva.ml/${"%s".replace(/(\w+) (\w+) (.+)/, "$1/$2/$3")}`);
```

This is a valid URL you can add as a Firefox bookmark search or a Chromium custom search. This way, instead of `!lva word` you could use the whole `!lva es zh word` query for selecting both languages and the query with a quick typing.

Hope this was useful to you.

Regards, David.

**Comment by milesmcclane** [comment]
Very useful @TheDavidDelta - thank you! Have a nice day.

**Comment by milesmcclane** [comment]
Hello again, sorry to reopen with a potentially silly problem! 

But I can’t get it to work. 

It returns:

The error was: "FetchEvent.respondWith
received an error: no-response: no-response
[f"url"."https://translate.<my domain>.com/auto/en/
salut"'}]"

I have tried the various options you outlined about with the exception of the last option as I’m currently just on my phone. 

I’m sorry to trouble you. 

Miles.

**Comment by TheDavidDelta** [comment]
Sorry, where are you trying this in?

**Comment by milesmcclane** [comment]
On iOS 15, using a Safari extension called xSearch. It’s a useful extension which enables a great deal more flexibility than Apple traditionally allows with Safari. 
It works fine with Google translate using the string mentioned in the OP..

**Comment by TheDavidDelta** [comment]
Make sure your domain was correctly set. Copy and paste the URL on your browser for checking what happens. It really doesn't make sense and anyway it's not on Lingva's side obviously, this is more like a problem related to the URL standard.

**Comment by milesmcclane** [comment]
The app xSearch works by using keywords. So if I type the keyword translate followed by bonjour, it should open to lingva ready translated - but it instead returns the error as above. 
However, if I just type the keyword and no other words to translate it does correctly open lingva. The problem seems to be with the search parameters rather than the url

**Comment by TheDavidDelta** [comment]
Open an issue in their repo.

**Comment by milesmcclane** [comment]
I have emailed them but they’re not as responsive as you! I’ll let you know the results when they get back to me. You’re right- it makes no sense.
