### ISSUE TITLE
translation_problem(russian): offensive language in translation

### ISSUE THREAD

**Issue by Kristinita** [TheDavidDelta/lingva-translate#69]
### 1. Summary

I got a hate speech word “педик” in the Lingva translation. I don’t reproduce the problem in Google Translate.

I would like this to be fixed. In addition, I would like if Lingva team to clarify how the offensive term appeared in the translation results.

### 2. Hate speech word

Lingva translated “queer kids” to “педиков”. See Russian [**dictionaries**](https://academic.ru/searchall.php?SWord=%D0%BF%D0%B5%D0%B4%D0%B8%D0%BA) and [**translation dictionaries**](https://translate.academic.ru/%D0%BF%D0%B5%D0%B4%D0%B8%D0%BA/ru/en/)꞉ “педик” in Russian means an offensive, derogatory word for a homosexual man. This word has about the same meaning as the English words “fag” and “faggot”.

### 3. Steps to reproduce

I copy the text from [**Google Books**](https://books.google.ru/books/about/Tendencies.html?id=RgKgFR-ArT0C)꞉

> The essays range from discussions of Diderot, Oscar Wilde and Henry James to queer kids, political correctness adn the poetics of spanking.

I selected translation from English to Russian → I translated this text on the official websites of Lingva and Google Translate.

#### 4.1. Lingva.ml

[**Lingva.ml translation**](https://lingva.ml/en/ru/The%20essays%20range%20from%20discussions%20of%20Diderot%2C%20Oscar%20Wilde%20and%20Henry%20James%20to%20queer%20kids%2C%20political%20correctness%20adn%20the%20poetics%20of%20spanking.) ([**archive copy**](https://archive.md/BUJS4))꞉

![Lingva.ml result](https://i.imgur.com/4VTYXaq.png)

#### 4.2. Google Translate

[**Google Translate translation**](https://translate.google.com/history?sl=en&tl=ru&text=The%20essays%20range%20from%20discussions%20of%20Diderot%2C%20Oscar%20Wilde%20and%20Henry%20James%20to%20queer%20kids%2C%20political%20correctness%20adn%20the%20poetics%20of%20spanking.&op=translate)꞉

![Google Translate result](https://i.imgur.com/VdL0eNI.png)

As you can see, Google Translate translated “queer kids” to “странные дети”, not to “педиков”.

Thanks.

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in the project.

I'm sorry you had an homophobic word in a translation.

I've taken a look at the provided links and I've reproduced the following results:

+ On the Lingva original translation, the cursed word is present:
![imagen](https://user-images.githubusercontent.com/6679900/141438971-a1f4aa71-6bb1-487a-a215-b086246a3bce.png)

+ But if you [remove the dot](https://lingva.ml/en/ru/The%20essays%20range%20from%20discussions%20of%20Diderot%2C%20Oscar%20Wilde%20and%20Henry%20James%20to%20queer%20kids%2C%20political%20correctness%20adn%20the%20poetics%20of%20spanking), it's not there anymore:
![imagen](https://user-images.githubusercontent.com/6679900/141439078-cd05a1e1-3d25-47f7-b494-99f6037de8f5.png)

+ On Google Translate, by [copying the same translation](https://translate.google.com/?sl=en&tl=ru&text=The%20essays%20range%20from%20discussions%20of%20Diderot%2C%20Oscar%20Wilde%20and%20Henry%20James%20to%20queer%20kids%2C%20political%20correctness%20adn%20the%20poetics%20of%20spanking.&op=translate) as the original (I can't access your history because I don't use a Google account) I receive the same result as in Lingva, with the cursed word:
![imagen](https://user-images.githubusercontent.com/6679900/141439333-aa1e6c2f-2ecd-4602-81f7-c2f41dea3435.png)

+ But, once again, if you [remove the final dot](https://translate.google.com/?sl=en&tl=ru&text=The%20essays%20range%20from%20discussions%20of%20Diderot%2C%20Oscar%20Wilde%20and%20Henry%20James%20to%20queer%20kids%2C%20political%20correctness%20adn%20the%20poetics%20of%20spanking&op=translate), the word is gone:
![imagen](https://user-images.githubusercontent.com/6679900/141439410-7e11a738-dfd7-4b15-b92d-3ca7317d2d73.png)

I don't know why this is happening to you, maybe Google is regionally discriminating some translations even though I don't think so and I encourage you to try translating it again in Google.

Anyway, as the only current member of the so-called "Lingva Team", I can tell you that the source code is completely public and you can check by yourself that everything we currently do is to scrape the GTranslate result.

Regards, David.

**Comment by TheFrenchGhosty** [comment]
@TheDavidDelta 

>I don't know why this is happening to you, maybe Google is regionally discriminating some translations even though I don't think so and I encourage you to try translating it again in Google.

Google is doing this, it's not news, and it's been proven multiples times: if more users "vote" for a translation in a country, it will be chosen for this country.
