### ISSUE TITLE
some question about this software

### ISSUE THREAD

**Issue by kucingkembar** [TheDavidDelta/lingva-translate#70]
hi, sorry for my bad English,
I have not installed this software, but I have some questions:
1. are this software can work offline (without connection from the internet)?
2. will in the near future, this software be available in python or Windows Command Line Interface(CMD/Batch/Powershell)?

thank you, have a nice day

**Comment by NS2555** [comment]
I am not the author of this project but i can answer the questions

This project is not software, but a web service, a self hostable web service that is, which basically means that you can only access it through the internet, and or, the provided API's.

1: No, this web application cannot work offline, due to it requiring constant contact with the google translate website to scrape the results off of.

2: This service provides a GQL API, and a REST API, so if you want to, you can implement the API in your application of choice by yourself. While I'm not sure you will be able to use it in scripts (probably with the exception of Powershell), you can for sure implement it in Python

**Comment by kucingkembar** [comment]
thank you for the reply NS2555,
i mark this question as solved

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in this project.

Sorry for taking this much time to reply. Luckily, @NS2555 already told you nearly everything. Thanks again Niko for being there solving questions :smile:
The only thing I may add, to the first question, is that even though Lingva is a web page and needs internet conection, it's built as a web application, with all the caching techniques needed to work as a Progressive Web App. This way, every page you visited previously is cached in your browser and can be acceded without internet connection. It can also be installed as a PWA on the [browsers that support them](https://caniuse.com/web-app-manifest).

Regards, David.
