### ISSUE TITLE
Third-party Lingva application

### ISSUE THREAD

**Issue by Kommprog** [TheDavidDelta/lingva-translate#71]
Hello.
Do you know there's a new [unofficial release ](https://play.google.com/store/apps/details?id=dev.atajan.lingva_android) of app (or maybe it's fork?) hosted on google store?

**Comment by TheDavidDelta** [comment]
Hey, thanks for letting me know!

It's not a fork, because Lingva is a webapp built with JavaScript and that one is an Android client that uses Lingva's public API.
Indeed, I'm aware of it. Its creator contacted me 2 days ago, letting me know its existence.

I asked him to change the name, not because it was illegal or unethical or something, at the end Lingva is a public and communal project, so I couldn't stop him, but as you have may noticed, it's confusing to people.
Indeed, most unofficial mobile clients of FOSS services usually have a custom name followed with the project's name (e.g., [Tusky for Mastodon](https://github.com/tuskyapp/Tusky), or simply Tusky).

But I'm still waiting for his reply. I'll be glad to add a link to his project (and any other Lingva-related project) inside the Readme once he changes the name.

I hope I've clarified your doubts.
Regards, David.
