### ISSUE TITLE
Open a Saved Language Setting

### ISSUE THREAD

**Issue by xenstar** [TheDavidDelta/lingva-translate#72]
Hello

Everytime, when I open the website, it opens with Detect Language and English. 

Also I tried with https://lingva.ml/en/zh/ but still it opens with detect language.

For me I frequently use Chinese to English and Vice Versa, can you make an option, so that we don't have to select language everytime?

**Comment by TheDavidDelta** [comment]
Hi and thanks for your interest in this project.

This indeed is already (at least partly) solved. A guy already requested last used languages to be 'saved' some time ago on #51 and got implemented on #52. So, by default, Lingva remembers the languages you used last time.

Another option for recurring translations is to use a Chromium custom search or Firefox bookmark search, as I explained more verbosely in #63. I have some for WordReference, Glosbe and Lingva myself.

But maybe what you want me to do is to implement an explicit menu for selecting default languages, right? This would collide with the current implementation (defaults to last used) but it may be implemented instead in a big refactor I have in mind for the future, in case most people prefer this way.

Hope I've helped.
Regards, David.

**Comment by xenstar** [comment]
I actually tried like this,

https://lingva.ml/zh/Is

So when I open this link, it does open as I want, but the link is redirected to https://lingva.ml/auto/zh/Is 

So when I create a shortcut to open the link on brave browser, it again opens with https://lingva.ml/auto/zh/Is (showing ls as a default word)

I can't also create a link with https://lingva.ml/auto/zh/ because it's redirected to https://lingva.ml/auto/auto/zh

It would be great, if you create an option, where we can save our default (last used), would be helpful for many people.

**Comment by thedaviddelta** [comment]
Hello again!

As I explained last time, if you want to save some default languages the easiest way is to let Lingva do it for you internally by using the browser's `localstorage`. Just make a translation with those languages, and the next time you open https://lingva.ml/ it will remember them.

The current 3 parameters behaviour is completely intentional. As also explained on the last message, it's not intended for bookmarking but for custom searching. You can get a complete explanation in the following issue: #63. That's the main and intended way, already used by many people, like myself, whose I would ruin if I changed it.

Regards, David.
