### ISSUE TITLE
Replacing caret while typing and editing text

### ISSUE THREAD

**Issue by Ygarr** [TheDavidDelta/lingva-translate#74]
While type text and then edit it,  the translator move caret to the end of text, so you need to manually return caret to right place. Or you text will be torn.

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in the project.

I'm sorry, but I think I haven't quite understood you. Do you mean that the cursor moves to the end of the textarea when submitting the translation?

Regards, David.

**Comment by Ygarr** [comment]
Thanks for reply. Almost
The cursor moves to the end of the text area without submitting the translation.
The submitting happens automatically. 
So while you editing inside text/in the middle - cursor carryover/jumps over to the end. 

You typed:
"And A And B"

Then you want to correct to 
"And A _And A1_ And B"

But you get 

"And A _An_ And B _d A1_"

**Comment by TheDavidDelta** [comment]
I still don't know if I understood completely.

It shouldn't submit automatically, except if you enable auto-translation (the lightning button). In that case, it may have some strange behaviours on auto-submiting.

It shouldn't be a big problem, but that's why we moved to defaulting the manual translation mode, as it's less prone to unexpected behaviours.

The submit issues are expected to be completely solved in an already-planed big refactor in the future, as they are inherent to the current architecture.

Hope I've helped.
Regards, David.
