### ISSUE TITLE
[FEATUER REQUEST] Enable suggestions of a wrong words?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [TheDavidDelta/lingva-translate#88]
As a non native english speaker I really *missspill* a lot of words and my main usage of google translation was accuracy and it's function to correct my weird words.
![image](https://user-images.githubusercontent.com/28893833/153132708-057f1641-60d3-4714-9884-38dea4568ecc.png)

Lingva already got accuracy as it pulls from google but now i lack option of correction, I think of 2 ways to solve this:
* Inside HTML. enable tag to let browser scan words and correct them [super easy] but corrections won't be as much as good 
* pull corrected words from google as you already pull translation [kinda hard] but it would be nice!

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in this project.

I'm glad to tell you that Lingva's main text area already detects and underlines incorrect words in the detected language (built-in spellcheck) in case it's activated in your browser.

About the second point, I'm sorry it can't be added for the moment. I did more extensive explanations in #8, but TLDR we're currently using the mobile version of GTranslate as it's very much easier and safer to scrape.
I still have a big refactor pending on Lingva, that may go towards that direction (or maybe towards adding other engines, it depends but it'll be only one of them).
I'll close this issue because it's very similar to what's requested in #8, that at the end is every possible feature from GTranslate, and shares the same underlying problem.

Regards, David.

**Comment by EsmailELBoBDev2** [comment]
Weird, it is activated but i do not see it this is why i said you can enable it? :joy: 

Also good luck with your idea to bring more of google translate in your lingva :)

**Comment by TheDavidDelta** [comment]
You can enable it on the browser config. In Firefox, it's in the languages section.
