### ISSUE TITLE
Auto dark mode

### ISSUE THREAD

**Issue by fariszr** [TheDavidDelta/lingva-translate#91]
Hi,
This is an awesome project!, I just have a small suggestion.

Instead of manually switching to or from light mode, why not follow the device's `prefer-color-scheme`?
I think it should be relatively easy to implement.

**Comment by TheDavidDelta** [comment]
Hi and thanks for your interest in this project.

Thanks for your suggestion! Indeed I already know about `prefer-color-scheme`, but I took the decission of sticking with manual color mode when building the project.
This was because I wanted to be able to manually switch the color scheme, and with `prefer-color-scheme` you are limited to your system's color scheme.

Anyway, instance owners can select the default color scheme for their instances, and the user preference gets stored in localStorage too!
But if the majority of the people preferes `prefer-color-scheme` over the current implementation, I will take it into account for the next Lingva refactor.

Regards, David.

**Comment by fariszr** [comment]
You can implement `prefer-color-scheme` while still having the theme button to override the system color scheme.

**Comment by TheDavidDelta** [comment]
I don't think so, because `prefer-color-scheme` uses CSS media queries, and can't be replaced that easy.
If I understand correctly, the stylesheet would have to be duplicated for both the `@media prefer-color-scheme` and the manual selection, adding `!important` to the manual ones.

Anyway, we currently use ChakraUI as our styling library for the project and [it doesn't support both](https://chakra-ui.com/docs/features/color-mode) either, I'm sorry :cry:.

Regards, David.

**Comment by thedaviddelta** [comment]
Hello again!
I'm glad to tell that this has finally been implemented in the last release (#113), thanks to a Chakra update!

Regards, David.
