### ISSUE TITLE
Display alternate translations

### ISSUE THREAD

**Issue by catwithbanana** [TheDavidDelta/lingva-translate#92]
When using Google Translate alternate translations are displayed for each word entered. This helps a lot when translating words that vary based on context or may have regional variations.

I see from #8 that Lingva has some limitations because it scrapes the mobile version of Translate. However, alternate translations are displayed on mobile translate, so the scraping shouldn't be an issue in this circumstance.

Thanks.

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in the project.

I'm sorry but the GTranslate mobile version doesn't display the alternative translations. Indeed this same thing was requested in the issue you are linking.

The [real old-GTranslate mobile version](https://translate.google.com/m), which we scrape, is a super simple HTML-based page. You are probably talking about the [standard GTranslate version](https://translate.google.com/), which currently gets displayed on mobile with a responsive design, instead of the old one.

Regards, David.
